
title: My Resume # your title
url: https://kjeld-schmidt.com
baseurl: "/coding-kind" # the subpath of your site, e.g. /blog



# Profile information
yourname: Brown Smith  ## put your name
location: San Francisco , CA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
